name: sm-attr-311
channels: [conda-forge]
dependencies:
  - python=3.11
  - xarray
  - netcdf4
  - cftime
  - numpy
  - pandas
  - pyyaml
  - bottleneck
  - pytest
  - dask
  - tqdm
  # viz
  - matplotlib
  - seaborn
  - cartopy
  - regionmask
  # regridding / ESMF stack
  - esmf
  - esmpy
  - xesmf
  # geospatial TIFF handling
  - rioxarray
  - rasterio
  # metrics
  - xskillscore
  # nc mask handling
  - geopandas
  - shapely
  - regionmask