# configs/data_registry.yml

paths:
  root: "/Users/thchilly/projects/sm_attribution/data"
  raw_models: "/Users/thchilly/projects/sm_attribution/data/models"
  raw_obs: "/Users/thchilly/projects/sm_attribution/data/observed"
  processed_models_1m: "/Users/thchilly/projects/sm_attribution/data/models_1m"
  processed_obs_1m: "/Users/thchilly/projects/sm_attribution/data/observed_1m"

naming_notes:
  obsclim: "observational (factual) climate"
  counterclim: "counterfactual climate"
  soc: "socioeconomic forcing; using histsoc and 1901soc for all models"

# --------------------------------------------------------------------
# RAW MODEL FILES (flat files, one per model+scenario)
# Four scenarios per model: obsclim_histsoc, counterclim_histsoc, obsclim_1901soc, counterclim_1901soc
models:
  h08:
    obsclim_histsoc:        "/Users/thchilly/projects/sm_attribution/data/models/h08_gswp3-w5e5_obsclim_histsoc_default_soilmoist_global_monthly_1901_2019.nc"
    counterclim_histsoc:    "/Users/thchilly/projects/sm_attribution/data/models/h08_gswp3-w5e5_counterclim_histsoc_default_soilmoist_global_monthly_1901_2019.nc"
    obsclim_1901soc:        "/Users/thchilly/projects/sm_attribution/data/models/h08_gswp3-w5e5_obsclim_1901soc_default_soilmoist_global_monthly_1901_2019.nc"
    counterclim_1901soc:    "/Users/thchilly/projects/sm_attribution/data/models/h08_gswp3-w5e5_counterclim_1901soc_default_soilmoist_global_monthly_1901_2019.nc"
    variable: "soilmoist"

  hydropy:
    obsclim_histsoc:        "/Users/thchilly/projects/sm_attribution/data/models/hydropy_gswp3-w5e5_obsclim_histsoc_default_rootmoist_global_monthly_1901_2019.nc"
    counterclim_histsoc:    "/Users/thchilly/projects/sm_attribution/data/models/hydropy_gswp3-w5e5_counterclim_histsoc_default_rootmoist_global_monthly_1901_2019.nc"
    obsclim_1901soc:        "/Users/thchilly/projects/sm_attribution/data/models/hydropy_gswp3-w5e5_obsclim_1901soc_default_rootmoist_global_monthly_1901_2019.nc"
    counterclim_1901soc:    "/Users/thchilly/projects/sm_attribution/data/models/hydropy_gswp3-w5e5_counterclim_1901soc_default_rootmoist_global_monthly_1901_2019.nc"
    variable: "rootmoist"   # different name; code should branch on this

  jules-w2:
    obsclim_histsoc:        "/Users/thchilly/projects/sm_attribution/data/models/jules-w2_gswp3-w5e5_obsclim_histsoc_default_soilmoist_global_monthly_1901_2019.nc"
    counterclim_histsoc:    "/Users/thchilly/projects/sm_attribution/data/models/jules-w2_gswp3-w5e5_counterclim_histsoc_default_soilmoist_global_monthly_1901_2019.nc"
    obsclim_1901soc:        "/Users/thchilly/projects/sm_attribution/data/models/jules-w2_gswp3-w5e5_obsclim_1901soc_default_soilmoist_global_monthly_1901_2019.nc"
    counterclim_1901soc:    "/Users/thchilly/projects/sm_attribution/data/models/jules-w2_gswp3-w5e5_counterclim_1901soc_default_soilmoist_global_monthly_1901_2019.nc"
    variable: "soilmoist"

  miroc-integ-land:
    obsclim_histsoc:        "/Users/thchilly/projects/sm_attribution/data/models/miroc-integ-land_gswp3-w5e5_obsclim_histsoc_default_soilmoist_global_monthly_1901_2019.nc"
    counterclim_histsoc:    "/Users/thchilly/projects/sm_attribution/data/models/miroc-integ-land_gswp3-w5e5_counterclim_histsoc_default_soilmoist_global_monthly_1901_2019.nc"
    obsclim_1901soc:        "/Users/thchilly/projects/sm_attribution/data/models/miroc-integ-land_gswp3-w5e5_obsclim_1901soc_default_soilmoist_global_monthly_1901_2019.nc"
    counterclim_1901soc:    "/Users/thchilly/projects/sm_attribution/data/models/miroc-integ-land_gswp3-w5e5_counterclim_1901soc_default_soilmoist_global_monthly_1901_2019.nc"
    variable: "soilmoist"

  watergap2-2e:
    obsclim_histsoc:        "/Users/thchilly/projects/sm_attribution/data/models/watergap2-2e_gswp3-w5e5_obsclim_histsoc_default_soilmoist_global_monthly_1901_2019.nc"
    counterclim_histsoc:    "/Users/thchilly/projects/sm_attribution/data/models/watergap2-2e_gswp3-w5e5_counterclim_histsoc_default_soilmoist_global_monthly_1901_2019.nc"
    obsclim_1901soc:        "/Users/thchilly/projects/sm_attribution/data/models/watergap2-2e_gswp3-w5e5_obsclim_1901soc_default_soilmoist_global_monthly_1901_2019.nc"
    counterclim_1901soc:    "/Users/thchilly/projects/sm_attribution/data/models/watergap2-2e_gswp3-w5e5_counterclim_1901soc_default_soilmoist_global_monthly_1901_2019.nc"
    variable: "soilmoist"

  web-dhm-sg:
    obsclim_histsoc:        "/Users/thchilly/projects/sm_attribution/data/models/web-dhm-sg_gswp3-w5e5_obsclim_histsoc_default_soilmoist_global_monthly_1901_2019.nc"
    counterclim_histsoc:    "/Users/thchilly/projects/sm_attribution/data/models/web-dhm-sg_gswp3-w5e5_counterclim_histsoc_default_soilmoist_global_monthly_1901_2019.nc"
    obsclim_1901soc:        "/Users/thchilly/projects/sm_attribution/data/models/web-dhm-sg_gswp3-w5e5_obsclim_1901soc_default_soilmoist_global_monthly_1901_2019.nc"
    counterclim_1901soc:    "/Users/thchilly/projects/sm_attribution/data/models/web-dhm-sg_gswp3-w5e5_counterclim_1901soc_default_soilmoist_global_monthly_1901_2019.nc"
    variable: "soilmoist"

  lpjml5-7-10-fire:
    obsclim_histsoc:        "/Users/thchilly/projects/sm_attribution/data/models/lpjml5-7-10-fire_gswp3-w5e5_obsclim_histsoc_default_soilmoist_global_monthly_1901_2019.nc"
    counterclim_histsoc:    "/Users/thchilly/projects/sm_attribution/data/models/lpjml5-7-10-fire_gswp3-w5e5_counterclim_histsoc_default_soilmoist_global_monthly_1901_2019.nc"
    obsclim_1901soc:        "/Users/thchilly/projects/sm_attribution/data/models/lpjml5-7-10-fire_gswp3-w5e5_obsclim_1901soc_default_soilmoist_global_monthly_1901_2019.nc"
    counterclim_1901soc:    "/Users/thchilly/projects/sm_attribution/data/models/lpjml5-7-10-fire_gswp3-w5e5_counterclim_1901soc_default_soilmoist_global_monthly_1901_2019.nc"
    variable: "soilmoist"

# --------------------------------------------------------------------
# RAW OBSERVATIONS (use only NetCDF/NC4; ignore .mat/.m files)
observations:
  era5:
    path: "/Users/thchilly/projects/sm_attribution/data/observed/ERA5/*.nc"
    notes: "Monthly files like sm1980.nc … sm2010.nc; ignore .mat/.m"
  gleam:
    path: "/Users/thchilly/projects/sm_attribution/data/observed/GLEAM/SMroot_*_GLEAM_v*.nc"
    notes: "Root-zone monthly; check depth assumptions when harmonizing to 0–1 m"
  gldas:
    path: "/Users/thchilly/projects/sm_attribution/data/observed/GLDASv2/*.nc4"
    notes: "NOAH 0.25°; pick correct variable and layers for 0–1 m integration"
  # grace: add if needed, for TWSA checks

# --------------------------------------------------------------------
# PROCESSED OUTPUTS — after homogenization to 0–1 m (models + observations)
processed:
  models_1m:
    h08:
      obsclim_histsoc:        "/Users/thchilly/projects/sm_attribution/data/models_1m/h08_gswp3-w5e5_obsclim_histsoc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      counterclim_histsoc:    "/Users/thchilly/projects/sm_attribution/data/models_1m/h08_gswp3-w5e5_counterclim_histsoc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      obsclim_1901soc:        "/Users/thchilly/projects/sm_attribution/data/models_1m/h08_gswp3-w5e5_obsclim_1901soc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      counterclim_1901soc:    "/Users/thchilly/projects/sm_attribution/data/models_1m/h08_gswp3-w5e5_counterclim_1901soc_default_soilmoist_global_monthly_1901_2019_1m.nc"
    hydropy:
      obsclim_histsoc:        "/Users/thchilly/projects/sm_attribution/data/models_1m/hydropy_gswp3-w5e5_obsclim_histsoc_default_rootmoist_global_monthly_1901_2019_1m.nc"
      counterclim_histsoc:    "/Users/thchilly/projects/sm_attribution/data/models_1m/hydropy_gswp3-w5e5_counterclim_histsoc_default_rootmoist_global_monthly_1901_2019_1m.nc"
      obsclim_1901soc:        "/Users/thchilly/projects/sm_attribution/data/models_1m/hydropy_gswp3-w5e5_obsclim_1901soc_default_rootmoist_global_monthly_1901_2019_1m.nc"
      counterclim_1901soc:    "/Users/thchilly/projects/sm_attribution/data/models_1m/hydropy_gswp3-w5e5_counterclim_1901soc_default_rootmoist_global_monthly_1901_2019_1m.nc"
    jules-w2:
      obsclim_histsoc:        "/Users/thchilly/projects/sm_attribution/data/models_1m/jules-w2_gswp3-w5e5_obsclim_histsoc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      counterclim_histsoc:    "/Users/thchilly/projects/sm_attribution/data/models_1m/jules-w2_gswp3-w5e5_counterclim_histsoc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      obsclim_1901soc:        "/Users/thchilly/projects/sm_attribution/data/models_1m/jules-w2_gswp3-w5e5_obsclim_1901soc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      counterclim_1901soc:    "/Users/thchilly/projects/sm_attribution/data/models_1m/jules-w2_gswp3-w5e5_counterclim_1901soc_default_soilmoist_global_monthly_1901_2019_1m.nc"
    miroc-integ-land:
      obsclim_histsoc:        "/Users/thchilly/projects/sm_attribution/data/models_1m/miroc-integ-land_gswp3-w5e5_obsclim_histsoc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      counterclim_histsoc:    "/Users/thchilly/projects/sm_attribution/data/models_1m/miroc-integ-land_gswp3-w5e5_counterclim_histsoc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      obsclim_1901soc:        "/Users/thchilly/projects/sm_attribution/data/models_1m/miroc-integ-land_gswp3-w5e5_obsclim_1901soc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      counterclim_1901soc:    "/Users/thchilly/projects/sm_attribution/data/models_1m/miroc-integ-land_gswp3-w5e5_counterclim_1901soc_default_soilmoist_global_monthly_1901_2019_1m.nc"
    watergap2-2e:
      obsclim_histsoc:        "/Users/thchilly/projects/sm_attribution/data/models_1m/watergap2-2e_gswp3-w5e5_obsclim_histsoc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      counterclim_histsoc:    "/Users/thchilly/projects/sm_attribution/data/models_1m/watergap2-2e_gswp3-w5e5_counterclim_histsoc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      obsclim_1901soc:        "/Users/thchilly/projects/sm_attribution/data/models_1m/watergap2-2e_gswp3-w5e5_obsclim_1901soc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      counterclim_1901soc:    "/Users/thchilly/projects/sm_attribution/data/models_1m/watergap2-2e_gswp3-w5e5_counterclim_1901soc_default_soilmoist_global_monthly_1901_2019_1m.nc"
    web-dhm-sg:
      obsclim_histsoc:        "/Users/thchilly/projects/sm_attribution/data/models_1m/web-dhm-sg_gswp3-w5e5_obsclim_histsoc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      counterclim_histsoc:    "/Users/thchilly/projects/sm_attribution/data/models_1m/web-dhm-sg_gswp3-w5e5_counterclim_histsoc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      obsclim_1901soc:        "/Users/thchilly/projects/sm_attribution/data/models_1m/web-dhm-sg_gswp3-w5e5_obsclim_1901soc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      counterclim_1901soc:    "/Users/thchilly/projects/sm_attribution/data/models_1m/web-dhm-sg_gswp3-w5e5_counterclim_1901soc_default_soilmoist_global_monthly_1901_2019_1m.nc"
    lpjml5-7-10-fire:
      obsclim_histsoc:        "/Users/thchilly/projects/sm_attribution/data/models_1m/lpjml5-7-10-fire_gswp3-w5e5_obsclim_histsoc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      counterclim_histsoc:    "/Users/thchilly/projects/sm_attribution/data/models_1m/lpjml5-7-10-fire_gswp3-w5e5_counterclim_histsoc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      obsclim_1901soc:        "/Users/thchilly/projects/sm_attribution/data/models_1m/lpjml5-7-10-fire_gswp3-w5e5_obsclim_1901soc_default_soilmoist_global_monthly_1901_2019_1m.nc"
      counterclim_1901soc:    "/Users/thchilly/projects/sm_attribution/data/models_1m/lpjml5-7-10-fire_gswp3-w5e5_counterclim_1901soc_default_soilmoist_global_monthly_1901_2019_1m.nc"

  observed_1m:
    era5:   "/Users/thchilly/projects/sm_attribution/data/observed_1m/ERA5/*.nc"
    gleam:  "/Users/thchilly/projects/sm_attribution/data/observed_1m/GLEAM/*.nc"
    gldas:  "/Users/thchilly/projects/sm_attribution/data/observed_1m/GLDASv2/*.nc"
